// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBudgetStmt, err = db.PrepareContext(ctx, createBudget); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBudget: %w", err)
	}
	if q.deleteBudgetStmt, err = db.PrepareContext(ctx, deleteBudget); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBudget: %w", err)
	}
	if q.getBudgetByIDStmt, err = db.PrepareContext(ctx, getBudgetByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBudgetByID: %w", err)
	}
	if q.getBudgetByUserIDStmt, err = db.PrepareContext(ctx, getBudgetByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBudgetByUserID: %w", err)
	}
	if q.getListBudgetStmt, err = db.PrepareContext(ctx, getListBudget); err != nil {
		return nil, fmt.Errorf("error preparing query GetListBudget: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBudgetStmt != nil {
		if cerr := q.createBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBudgetStmt: %w", cerr)
		}
	}
	if q.deleteBudgetStmt != nil {
		if cerr := q.deleteBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBudgetStmt: %w", cerr)
		}
	}
	if q.getBudgetByIDStmt != nil {
		if cerr := q.getBudgetByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBudgetByIDStmt: %w", cerr)
		}
	}
	if q.getBudgetByUserIDStmt != nil {
		if cerr := q.getBudgetByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBudgetByUserIDStmt: %w", cerr)
		}
	}
	if q.getListBudgetStmt != nil {
		if cerr := q.getListBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getListBudgetStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	createBudgetStmt      *sql.Stmt
	deleteBudgetStmt      *sql.Stmt
	getBudgetByIDStmt     *sql.Stmt
	getBudgetByUserIDStmt *sql.Stmt
	getListBudgetStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		createBudgetStmt:      q.createBudgetStmt,
		deleteBudgetStmt:      q.deleteBudgetStmt,
		getBudgetByIDStmt:     q.getBudgetByIDStmt,
		getBudgetByUserIDStmt: q.getBudgetByUserIDStmt,
		getListBudgetStmt:     q.getListBudgetStmt,
	}
}
